### ISSUE TITLE
Cannot install Mobile UI

### ISSUE THREAD

**Issue by RajSolai** [MobileUI/components#128]
$ mobileui
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\Solai\AppData\Roaming\npm\node_modules\mobileui\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Solai\AppData\Roaming\npm\node_modules\mobileui\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Solai\AppData\Roaming\npm\node_modules\mobileui\node_modules\fstream\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by jhurliman** [comment]
This is a hacky workaround, but for now:

```
sudo npm install -g n
sudo n 11.15.0
mobileui
```

**Comment by alzf** [comment]
same problem here, and that suggested workaround didn´t work for me.

**Comment by atmanegara** [comment]
downgrade node js version < 12

**Comment by fabiorogeriosj** [comment]
I refactor request to axios and generate version 2.x, now it is ok!
