### ISSUE TITLE
Imcompatibilidade com a versão 12 LTS do Node

### ISSUE THREAD

**Issue by Alexandre-Muzulao** [MobileUI/components#132]
Apenas de atualizar a versão do node na máquina, já aparece o problema quando executa o mobileui prevew:

` mobileui preview
fs.js:35
} = primordials;
    ^
ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\alexandre.muzulao\AppData\Roaming\npm\node_modules\mobileui\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\alexandre.muzulao\AppData\Roaming\npm\node_modules\mobileui\node_modules\natives\index.js:55:10)`

**Comment by dnspsv** [comment]
Eu também estou tendo o mesmo problema.

**Comment by lordpt** [comment]
infelizmente também com o mesmo problema por aqui, a solução passou por fazer o downgrade do Node 12 para o Node 11
