### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by peppos80** [MobileUI/components#144]
when i try to install mobileui go on error:

 npx npm-force-resolutions

┌────────────────────────────────────────────────────────────────────┐
│                      npm update check failed                       │
│                Try running with sudo or get access                 │
│                to the local update config store via                │
│ sudo chown -R $USER:$(id -gn $USER) /Users/giuseppemacchia/.config │
└────────────────────────────────────────────────────────────────────┘
npx: installato 6 in 3.716s
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (fs.js:448:3)
    at Object.fs [as readFileSync] (fs.js:348:35)
    at npm_force_resolutions$core$node_slurp (/Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
    at npm_force_resolutions$core$read_json (/Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:22:23)
    at switch__2144__auto__ (/Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at /Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (/Users/giuseppemacchia/.npm/_npx/1565/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
npm WARN ws@7.4.4 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.4 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mobileui@1.1.20 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mobileui@1.1.20 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/giuseppemacchia/.npm/_logs/2021-04-01T22_50_07_494Z-debug.log

**Comment by Alexandre-Muzulao** [comment]
I Have the same problem!

**Comment by angelogiuseppe** [comment]
To anyone experiencing this issue, feel free to try: https://www.npmjs.com/package/force-resolutions

**Just change:**

```json
"preinstall": "npx npm-force-resolutions"
```
**To:**

```json
"preinstall": "npx force-resolutions"
```


npx force-resolutions does not run when no package-lock.json is detected, and allows the next command inline to be executed as normal. This is useful when installing dependencies for a package that has been already published where package-lock.json is not available.

Feedback and PR's are welcome

**Comment by Alexandre-Muzulao** [comment]
@angelogiuseppe this does not work!

**Comment by fabiorogeriosj** [comment]
I refactor request to axios and generate version 2.x, now it is ok!
